version: '3.8'

networks:
  app-network:
    driver: bridge

services:

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webflux-onb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network

  localstack:
    image: localstack/localstack:latest
    container_name: localstack-container
    environment:
      - SERVICES=s3,lambda,sqs,dynamodb
    ports:
      - "4566-4599:4566-4599"
    volumes:
      - ./init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    container_name: my-app-container
    depends_on:
      - postgres
      - redis
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=fakeAccessKey
      - AWS_SECRET_ACCESS_KEY=fakeSecretKey
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "8080:8080"
    command: [ "sh", "-c", "./wait-for-it.sh postgres:5432 -- ./wait-for-it.sh localstack:4566 -- ./wait-for-it.sh redis:6379 -- java -jar reactive-workshop.jar" ]
    networks:
      - app-network

volumes:
  postgres-data:

